export const pages = [
  { id: "welcome", label: "歡迎頁" },
  { id: "login", label: "登入" },
  { id: "signup", label: "註冊" },
  { id: "placement", label: "程度測驗" },
  { id: "home", label: "首頁" },
  { id: "path", label: "學習路徑" },
  { id: "lesson", label: "課程詳情" },
  { id: "practice", label: "口說練習" },
  { id: "freetalk", label: "自由對話" },
  { id: "summary", label: "課後總結" },
  { id: "review", label: "複習中心" },
  { id: "subscription", label: "訂閱方案" },
  { id: "profile", label: "個人設定" },
  { id: "support", label: "客服支援" },
];
